import React from "react";
import Link from "next/link";
import {Metadata} from "next";
import GetUsers from "./lib/getAllUsers";


export const metadata = {
  title: "Users",
  description: "Generated by create next app",
};

const Fallguys = [
  {
    id:1,
    title:"Busting a nut",
    willy:"Wanking state200",
  },
  {
    id:2,
    title:"Throwing yo boi",
    willy:"Nicholas Cage",
  },
]


export default function AboutLayout({ children }) {
 
  return (
    <div >
      <h1>About</h1>
      {Fallguys.length === 0 ? <p>Nothing to see here </p> : (
        Fallguys.map((x)=>{
          <div key={x.id}>
          <p>{x.id} {x.title}</p>
          <p>KUMMMMMMMMMMMM {x.willy}</p>
          </div>
        })
      )}
      <Link href="/users">Get Users</Link>
      <Link href="/">Link to home</Link>
    </div>
  );
}


